### ISSUE TITLE
Plan to fix after CRAN archive

### ISSUE THREAD

**Issue by timcdlucas** [kevinushey/Kmisc#13]
Hi,

I just thought I'd ask if there's plans to get this package back on CRAN as it's been archived? I've inherited some code that uses functions from this package and I'm just trying to work out what the best course of action is for me (and future maintainers of the code).

Thanks a lot in advance.

**Comment by kevinushey** [comment]
Sorry, there are no plans to re-release to CRAN. I'd recommend installing from GitHub with e.g.

```
remotes::install_github("kevinushey/Kmisc")
```

If installing packages from GitHub isn't an option, let me know what functions you're using and I'll try to recommend a replacement.

**Comment by timcdlucas** [comment]
Thank you very much. I'm currently using install_github. I'll just decide whether it's worth the hassle for future maintainers.

Tim
